INSERT INTO deposit_schemes (
    branch_id,
    scheme_id,
    scheme_name,
    scheme_description,
    deposit_type,
    minimum_deposit,
    maximum_deposit,
    minimum_period_months,
    maximum_period_months,
    interest_rate,
    interest_code,
    interest_frequency,
    interest_calculation_method,
    premature_closure_allowed,
    premature_penal_rate,
    auto_renewal_allowed,
    tds_applicable,
    deposit_gl_account,
    interest_payable_gl_account,
    interest_expense_gl_account,
    penal_interest_gl_account
) VALUES (
    2310801,
    22001,
    'Term Deposit Non Cumulative',
    'Fixed deposit with periodic interest payout',
    'TERM',
    1000.00,
    10000000.00,
    3,
    120,
    7.00,
    0,
    'QUARTERLY',
    'SIMPLE',
    true,
    1.00,
    true,
    true,
    '12201000',
    '0',   -- Interest Payable GL (you must create if not exists)
    '41201000',
    NULL
);


INSERT INTO deposit_schemes (
    branch_id,
    scheme_id,
    scheme_name,
    scheme_description,
    deposit_type,
    minimum_deposit,
    maximum_deposit,
    minimum_period_months,
    maximum_period_months,
    interest_rate,
    interest_code,
    interest_frequency,
    interest_calculation_method,
    compounding_frequency,
    premature_closure_allowed,
    premature_penal_rate,
    auto_renewal_allowed,
    tds_applicable,
    deposit_gl_account,
    interest_payable_gl_account,
    interest_expense_gl_account
) VALUES (
    2310801,
    22002,
    'Term Deposit Cumulative',
    'Fixed deposit with interest compounded till maturity',
    'TERM',
    1000.00,
    10000000.00,
    6,
    120,
    7.25,
    0,
    'ON_MATURITY',
    'COMPOUND',
    'QUARTERLY',
    true,
    1.00,
    true,
    true,
    '12202000',
    '0',
    '41202000'
);

INSERT INTO deposit_schemes (
    branch_id,
    scheme_id,
    scheme_name,
    scheme_description,
    deposit_type,
    minimum_deposit,
    maximum_deposit,
    minimum_period_months,
    maximum_period_months,
    installment_frequency,
    minimum_installment_amount,
    maximum_installment_amount,
    penal_rate,
    interest_rate,
    interest_code,
    interest_frequency,
    interest_calculation_method,
    premature_closure_allowed,
    premature_penal_rate,
    tds_applicable,
    deposit_gl_account,
    interest_payable_gl_account,
    interest_expense_gl_account
) VALUES (
    2310801,
    23001,
    'Recurring Deposit Non Cumulative',
    'Monthly installment deposit with periodic interest payout',
    'RECURRING',
    0.00,
    0.00,
    6,
    120,
    'MONTHLY',
    500.00,
    100000.00,
    2.00,
    6.75,
    0,
    'ON_MATURITY',
    'SIMPLE',
    true,
    1.00,
    true,
    '12301000',
    '0',
    '41301000'
);


INSERT INTO deposit_schemes (
    branch_id,
    scheme_id,
    scheme_name,
    scheme_description,
    deposit_type,
    minimum_period_months,
    maximum_period_months,
    installment_frequency,
    minimum_installment_amount,
    maximum_installment_amount,
    penal_rate,
    interest_rate,
    interest_code,
    interest_frequency,
    interest_calculation_method,
    compounding_frequency,
    premature_closure_allowed,
    premature_penal_rate,
    tds_applicable,
    deposit_gl_account,
    interest_payable_gl_account,
    interest_expense_gl_account
) VALUES (
    2310801,
    23001,
    'Recurring Deposit Cumulative',
    'Monthly installment deposit with compounded interest till maturity',
    'RECURRING',
    12,
    120,
    'MONTHLY',
    500.00,
    100000.00,
    2.00,
    7.00,
    0,
    'ON_MATURITY',
    'COMPOUND',
    'QUARTERLY',
    true,
    1.00,
    true,
    '12302000',
    '0',
    '41302000'
);
