create table public.deposit_scheme_master (
  id uuid not null default gen_random_uuid (),
  scheme_id integer not null,
  scheme_name character varying(100) not null,
  scheme_description text null,
  deposit_type character varying(20) not null,
  minimum_deposit numeric(14, 2) not null default 0.00,
  maximum_deposit numeric(14, 2) not null default 0.00,
  minimum_period_months integer null default 0,
  maximum_period_months integer null default 0,
  minimum_period_days integer null default 0,
  maximum_period_days integer null default 0,
  installment_frequency character varying(20) null,
  minimum_installment_amount numeric(14, 2) null default 0.00,
  maximum_installment_amount numeric(14, 2) null default 0.00,
  penal_rate numeric(5, 2) null default 0.00,
  collection_frequency character varying(20) null,
  agent_commission_percent numeric(5, 2) null default 0.00,
  interest_policy_id character varying(20) not null,
  interest_rate numeric(5, 2) not null default 0.00,
  interest_frequency character varying(20) not null default 'ON_MATURITY'::character varying,
  interest_calculation_method character varying(20) not null default 'SIMPLE'::character varying,
  compounding_frequency character varying(20) null,
  interest_rounding character varying(20) null default 'NEAREST'::character varying,
  minimum_interest_payable numeric(14, 2) null default 0.00,
  premature_closure_allowed boolean not null default true,
  premature_penal_rate numeric(5, 2) null default 0.00,
  auto_renewal_allowed boolean not null default false,
  tds_applicable boolean not null default false,
  deposit_gl_account character varying(20) not null,
  interest_payable_gl_account character varying(20) not null,
  interest_expense_gl_account character varying(20) not null,
  penal_interest_gl_account character varying(20) null,
  minimum_age integer null default 0,
  maximum_age integer null default 0,
  is_staff_only boolean not null default false,
  scheme_status character varying(20) not null default 'ACTIVE'::character varying,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null default CURRENT_TIMESTAMP,
  penalty_allowed boolean not null default false,
  penalty_gl_account_no character varying(20) null,
  constraint deposit_scheme_master_pkey primary key (id),
  constraint deposit_scheme_master_scheme_id_key unique (scheme_id),
  constraint deposit_scheme_master_scheme_name_key unique (scheme_name)
) TABLESPACE pg_default;

create table public.loan_scheme_master (
  id uuid not null default gen_random_uuid (),
  scheme_id integer not null,
  scheme_name text not null,
  scheme_description text null,
  loan_type character varying(30) not null,
  minimum_loan_amount numeric(14, 2) not null default 0.00,
  maximum_loan_amount numeric(14, 2) not null default 0.00,
  minimum_period_months integer not null default 0,
  maximum_period_months integer not null default 0,
  repayment_frequency character varying(20) not null default 'MONTHLY'::character varying,
  installment_calculation_method character varying(20) not null default 'EMI'::character varying,
  interest_policy_id character varying(20) not null,
  interest_rate numeric(5, 2) not null default 0.00,
  interest_calculation_method character varying(20) not null default 'REDUCING_BALANCE'::character varying,
  interest_frequency character varying(20) not null default 'MONTHLY'::character varying,
  compounding_frequency character varying(20) null,
  interest_rounding character varying(20) not null default 'NEAREST'::character varying,
  minimum_interest_payable numeric(14, 2) not null default 0.00,
  penal_interest_rate numeric(5, 2) null default 0.00,
  penalty_grace_days integer null default 0,
  processing_fee_percent numeric(5, 2) null default 0.00,
  processing_fee_min numeric(14, 2) null default 0.00,
  processing_fee_max numeric(14, 2) null default 0.00,
  prepayment_allowed boolean not null default true,
  prepayment_penalty_percent numeric(5, 2) null default 0.00,
  collateral_required boolean not null default false,
  loan_gl_account character varying(20) not null,
  interest_income_gl_account character varying(20) not null,
  interest_receivable_gl_account character varying(20) not null,
  penal_interest_gl_account character varying(20) null,
  processing_fee_gl_account character varying(20) null,
  minimum_age integer null default 18,
  maximum_age integer null default 70,
  is_staff_only boolean not null default false,
  scheme_status character varying(20) not null default 'ACTIVE'::character varying,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null default CURRENT_TIMESTAMP,
  appraiser_charge_allowed boolean not null default false,
  appraiser_charge_code character varying(20) null,
  appraiser_name character varying(50) null,
  appraiser_amount_receive_account_number character varying(20) null,
  constraint loan_scheme_master_pkey primary key (id),
  constraint loan_scheme_master_scheme_id_key unique (scheme_id),
  constraint loan_scheme_master_scheme_name_key unique (scheme_name)
) TABLESPACE pg_default;


create table public.savings_scheme_master (
  id uuid not null default gen_random_uuid (),
  scheme_id integer not null,
  scheme_name character varying(100) not null,
  scheme_description text null,
  min_balance numeric(12, 2) not null default 0.00,
  interest_code character varying(20) not null,
  interest_rate numeric(5, 2) not null default 0.00,
  minimum_deposit numeric(12, 2) not null default 0.00,
  maximum_deposit numeric(12, 2) not null default 0.00,
  interest_frequency character varying(20) not null default 'QUARTERLY'::character varying,
  interest_calculation_method character varying(20) not null default 'DAILY_BALANCE'::character varying,
  interest_rounding character varying(20) not null default 'NEAREST'::character varying,
  minimum_balance_for_interest numeric(12, 2) not null default 0.00,
  minimum_interest_payable numeric(12, 2) not null default 0.00,
  savings_gl_account bigint not null,
  interest_payable_gl_account character varying(20) not null default 'null'::character varying,
  interest_paid_gl_account character varying(20) not null default 'null'::character varying,
  last_interest_calculated_date date null,
  minimum_age integer not null default 0,
  maximum_age integer not null default 0,
  is_staff_only boolean not null default false,
  scheme_status character varying(20) not null default 'ACTIVE'::character varying,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone null default CURRENT_TIMESTAMP,
  interest_payable_allowed boolean not null default false,
  constraint savings_scheme_master_pkey primary key (id),
  constraint savings_scheme_master_scheme_id_key unique (scheme_id),
  constraint savings_scheme_master_scheme_name_key unique (scheme_name),
  constraint savings_scheme_master_interest_code_fkey foreign KEY (interest_code) references savings_interest_codes (interest_code)
) TABLESPACE pg_default;